// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RFi22MmniHyRguW3VDK9xpV4brqyPlM',
    appId: '1:303254267360:web:2cd95231002761abe4b785',
    messagingSenderId: '303254267360',
    projectId: 'curosync-app',
    authDomain: 'curosync-app.firebaseapp.com',
    storageBucket: 'curosync-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvUxCAa5qiaCC0ff4MuL6bGLpe6p10dms',
    appId: '1:303254267360:android:764147d55e4b770be4b785',
    messagingSenderId: '303254267360',
    projectId: 'curosync-app',
    storageBucket: 'curosync-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucmNA5iQ0Oqn34nC8FGMYVuqHIdHO3GQ',
    appId: '1:303254267360:ios:d27b1e3b2c7714cde4b785',
    messagingSenderId: '303254267360',
    projectId: 'curosync-app',
    storageBucket: 'curosync-app.firebasestorage.app',
    iosBundleId: 'com.curosync.curosync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCucmNA5iQ0Oqn34nC8FGMYVuqHIdHO3GQ',
    appId: '1:303254267360:ios:d27b1e3b2c7714cde4b785',
    messagingSenderId: '303254267360',
    projectId: 'curosync-app',
    storageBucket: 'curosync-app.firebasestorage.app',
    iosBundleId: 'com.curosync.curosync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_RFi22MmniHyRguW3VDK9xpV4brqyPlM',
    appId: '1:303254267360:web:836ead6c8cac2992e4b785',
    messagingSenderId: '303254267360',
    projectId: 'curosync-app',
    authDomain: 'curosync-app.firebaseapp.com',
    storageBucket: 'curosync-app.firebasestorage.app',
  );

}